# Habilitar H2
quarkus.datasource.db-kind=h2

# URL de la base de datos (ejemplo: base de datos en memoria llamada 'testdb')
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb

# Credenciales
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Drop and create (útil en desarrollo)
quarkus.hibernate-orm.database.generation=drop-and-create
